custom_components/entity_controller/__init__.py
If `self.block_timeout` is not set then `self.block_timer_handle` will not be initialized.  So we need to add an extra check to ensure it's not `None` before accessing any attributes.  This addresses #37
=> Check that the block timer handle is not None before accessing attr.

custom_components/entity_controller/__init__.py
Otherwise callbacks end up on thread executor, which can be called concurrently.
Related to #61, but not tested that it solves it.
**Please open an issue** before embarking on any significant pull request, especially those that
add a new library or change existing tests, otherwise you risk spending a lot of time working
on something that might not end up being merged into the project.
**IMPORTANT**: By submitting a patch, you agree to allow the project
owners to license your work under the terms of the MIT License.
=> Add callback marker to keep calls in the event loop

custom_components/entity_controller/__init__.py
We must use async_call now that things run in the event loop, otherwise we can deadlock.
**IMPORTANT**: By submitting a patch, you agree to allow the project
owners to license your work under the terms of the MIT License.
=> Async call for service call

custom_components/entity_controller/__init__.py
Logger used in Home Assistant doesn't seem to have `trace` log severity,
thus I propose going for `debug` instead (right now this crashes my HA).
=> Use 'debug' in place of 'trace' logging

README.md, custom_components/entity_controller/__init__.py, custom_components/entity_controller/const.py, custom_components/entity_controller/entity_services.py, custom_components/entity_controller/services.yaml
This is my initial buildout of a services approach. It provides the following services.
clear_block -- this will clear the blocked state, and reset the block timer
set_stay_on -- this will set the stay flag to true to force stay on on the next activate
set_stay_off -- this will set the stay flag false to allow the controller to turn the light off after the next activate
set_night_mode -- this will change the start and end times for night mode. Added an additional now and constraint value support so the mode can be started/ended right now or when the day constraint time, also having both start and end unset sets them to midnight which should disable night mode.
In response to #125 but may have impact on other issues.
Also a possible idea to start #136 as I attempted to start moving content …
=> Initial services buildout

custom_components/entity_controller/__init__.py
Separates entity name and friendly name.  Entities will be created based on the YAML section name but will respect friendly name in frontend.  This is a breaking change.  
Also, defers to constant ATTR_FRIENDLY_NAME instead of using hardcoded "friendly_name".  
Adds friendly name listing to debug dump.  
Now based on develop branch.  
Please check line 94 in __init__.py as I'm not fully familiar with voluptuous.
=> Entity ID separate from friendly name

README.md, custom_components/entity_controller/__init__.py, custom_components/entity_controller/const.py, custom_components/entity_controller/entity_services.py
This PR implements transition behaviours as to allow some change to the behaviour. Cleans up implemention added in v6.0.0 and extends the number of transition points.
The behaviour implemented with `end_time_action` and `start_time_action` has been replaced with a more generic callback to make it the same as the other callbacks.
```
behaviours:
on_enter_constrain: "ignore"
on_exit_constrain: "ignore"
```
Closes #154
=> Transition Behaviours Extended

custom_components/entity_controller/__init__.py
Fix mdi icon names introduced in 0.113 and due to be removed in 0.115 https://www.home-assistant.io/blog/2020/07/22/release-113/#mdi-icons-updated
Closes n/a
=> Change mdi:timer* to mdi:timer*-outline in prep for HA 0.115

README.md, custom_components/entity_controller/__init__.py, custom_components/entity_controller/const.py, custom_components/entity_controller/entity_services.py
BREAKING CHANGE: Check the docs for new `stay_mode` configuration field and the name changes to the related services.
Closes #143
=> feat!: rename stay mode to make the feature easier to understand (#176)

custom_components/entity_controller/__init__.py, custom_components/entity_controller/const.py
This PR replaces the implementation of `grace_period` introduced in # with the Context API. This allows EC to detect state changes that EC itself triggered by calling a services. These state changes are ignored by EC and therefore no longer interfere.
The configurable `grace_period` configuration will be deprecrated in this release.
Closes #192
=> Implement Home Assistant Context API to avoid EC blocking itself (replaces grace_period)

custom_components/entity_controller/__init__.py
Fix support for [packages](https://www.home-assistant.io/docs/configuration/packages/) in HA configuration by iterating all `entity_controller:` keys. This allows users to separate the EC configuration into multiple files.
A basic …
=> fix: Apply all EC configurations in HA config packages

custom_components/entity_controller/__init__.py
This is after a request here https://github.com/home-assistant/core/pull/40626#issuecomment-709373896.
Closes https://github.com/danobot/entity-controller/issues/205
@broyuken, I don't use this integration, could you test if this works with the pattern `adapt_lgt_.*`.
Also, could you add documentation for this feature?
**IMPORTANT**: By submitting a patch, you agree to …
=> feat: Allow 'ignored_event_sources' to contain Regex patterns to support integrations with dynamic context ids

custom_components/entity_controller/manifest.json
Add `after_dependencies` on the most commonly used control entity components to prevent attempts to use them during startup before they have been initialised. This fixes `ServiceNotFound` with `Unable to find service light/turn_on` and `Unable to find service script/turn_on`.
Closes
=> fix: Exceptions due to services not loaded during EC startup

custom_components/entity_controller/__init__.py
Override `entity.Entity.should_poll` to indicate that Home Assistant does not need to poll Entity Controller entities for state changes.
Closes
=> fix: HA does not need to poll EC for state

custom_components/entity_controller/__init__.py, custom_components/entity_controller/const.py
When a triggering event occurs (entity state changes), create a new context ID and tie it to the state change's context via the `parent_id`. Also set this new context in the EC Entity.
This will allow better tracking of causes and effects in the logbook, which should now display when EC performs an action.
Closes
=> fix: Use unique Contexts to track cause and effect

custom_components/entity_controller/manifest.json
This is required for `homeassistant.util.uuid.random_uuid_hex`.
Closes
=> fix: Bump minimum HA version to 0.117.0

custom_components/entity_controller/__init__.py
When a zigbee2mqtt and zwave2mqtt motion sensor changes from motion to no motion detected it triggers two state changes:
the first only attribute changes with both old and new state: on
immediately follow by a second one where the state changes from on to off
the first is seen by EC as sensor on state change which gives unexpected results
Closes
#58
#227
=> fix: ignore sensor attribute only state changes

custom_components/entity_controller/__init__.py, custom_components/entity_controller/const.py, custom_components/entity_controller/entity_services.py, custom_components/entity_controller/services.yaml
I've added an `entity_controller.activate` service that can be used to manually activate an entity controller. This will transition from `idle` or `blocked` into `active`. It will also reset the timer if the state is already `active_timer`.
I am going to be using this to set up scheduled automations for devices around my house. For example, I will call this service to turn on our heated towel rails at 6am so that our towels are warm in the morning, and I will use the entity controller timer to turn off the heated towel rail after the timer expires. I also have a humidity sensor configured as a "hygrostat". This is a sensor that activates the entity controller and turns on the heated towel rails whenever someone is in the shower. So I want the scheduled timer and hygrostat to work together …
=> Add an "activate" service to manually activate an entity controller

custom_components/entity_controller/__init__.py, custom_components/entity_controller/const.py
* Ignore state change events for 70 seconds after starting
* Check overrides 65 seconds after starting (when entity states should be ready)
Not sure about the hardcoded `STARTUP_DELAY = 70`, since every installation will have different startup times and entities from different integrations. This is probably quite specific to my HA instance running on a server, and with most of my entities coming from Zigbee2MQTT. I also wouldn't want to need to configure this for every single entity controller instance. Not sure if there's a nice way to make this configurable.
This fixes an annoying issue I've experienced where I can't work on my HA config or perform upgrades late at night, because it would always turn on the bedroom lights while my wife was sleeping.
**Please open an issue** before …
=> Ignore state change events while Home Assistant is starting and initializing entity states, override controllers correctly on startup

custom_components/entity_controller/__init__.py
By returning None in except block, checking of remaining entities is prevented, even if there are functinoal one behind the broken on in the list.
By jumping skipping the rest of the loop, checking of the remaining entities is allowed, while the normal behaviour remains the same.
#313
Closes
=> Fix: Allow remaining entites to be checked, when one is potential configuartion error #313

custom_components/entity_controller/__init__.py
With this pull request i want to introduce a error message, if the home assistant and system timezones are mismatched.
This may cause the start_time_callback function to get called repeatedly.
With this change the user should become aware, that their current configuration might be an issue.
- [x ] The PR title is clear, concise and follows [`conventional commit`](https://www.conventionalcommits.org) formatting.
- [x ] Double-check your branch is based on `develop` and targets `develop` 
- [x ] Issue raised to compliment this PR (if no pre-existing issue exists)
- [x ] Description explains the issue/use-case resolved and auto-closes related issues.
- [x ] Testing of new changes completed by person who raised the issue.
**Please open an issue** before embarking on any significant pull …
=> feat: warn about mismatched timezones #311

custom_components/entity_controller/__init__.py
Throws warnings in 2024.5+
See https://developers.home-assistant.io/blog/2024/04/13/deprecate_async_track_state_change/
Note that the component still doesn't work properly under 2024.5; see #326 .
Closes
=> Replace async_track_state_change with async_track_state_change_event
