- custom_components/entity_controller/__init__.py
Validate the entities exist. Log and continue if they do not.
> check for valid entities

- custom_components/entity_controller/__init__.py
> Remove surplus whitespace.

- hacs.json
Fixes #82 and https://github.com/custom-components/hacs/issues/630
_I ignored your PULL template since the content of it did not match this repository at all_ :)
> Remove wrong values

- README.md
- custom_components/entity_controller/__init__.py
**Please open an issue** before embarking on any significant pull request, especially those that
add a new library or change existing tests, otherwise you risk spending a lot of time working
on something that might not end up being merged into the project.
**IMPORTANT**: By submitting a patch, you agree to allow the project
owners to license your work under the terms of the MIT License.
Closes #109
> Allow customization of which attribute changes are considered a manual change

- custom_components/entity_controller/__init__.py
Sharing this in case you'd like to incorporate it into your code. Formatted the code with Black as per the Home Assistant style guidelines.
https://developers.home-assistant.io/docs/en/development_guidelines.html
I know everyone has their taste and opinions; by no means am I saying you need to follow these guidelines.  My dev box is setup to automatically format everything per HA guidelines so I thought I'd share it.
N/A
> Black formatting, Import Sort, Logger Update.

- custom_components/entity_controller/__init__.py
- custom_components/entity_controller/services.yaml
Implement basic services (toggle, on, off, control) for the entity_controller domain.
**NOTE**: This is a preliminary framework for services. It still needs to be expanded to actually control the entity_controller. Just pushing now for initial testing.
#125 
#106
> Implements Basic Services and Control

- README.md
- hass-demo/secrets.yaml
> docs: update

- COPYING
- license.md
> Update and rename license.md to COPYING

- README.md
- custom_components/entity_controller/__init__.py
- custom_components/entity_controller/const.py
> Transition behaviours

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- custom_components/entity_controller/__init__.py
- loadbeta.sh
Various defect fixes included in this release.
**IMPORTANT**: By submitting a patch, you agree to allow the project owners to license your work under the terms of the project license
Closes #174 
Closes #173
Closes #98
Closes #164 
Closes #170
> Various Defect Fixes

- README.md
- custom_components/entity_controller/__init__.py
- custom_components/entity_controller/const.py
- custom_components/entity_controller/entity_services.py
Note the branch name uses an incorrect issue number.
Closes #143
> Rename stay mode for better understanding

- CHANGELOG.md
- README.md
- custom_components/entity_controller/__init__.py
- custom_components/entity_controller/const.py
- custom_components/entity_controller/entity_services.py
- package-lock.json
- package.json
> Merge Master to Develop

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
> chore: bug report

- custom_components/entity_controller/manifest.json
There is a typo in the name for hacs.  Missing an r
Closes
> Typo in name in hacs

- custom_components/entity_controller/__init__.py
- custom_components/entity_controller/manifest.json
> Version key

- custom_components/entity_controller/__init__.py
- custom_components/entity_controller/manifest.json
* Update __init__.py
Bump version to 9.2.2.
* Update manifest.json
fix: add version key to manifest
Closes
> fix: Version key (#243)

- custom_components/entity_controller/manifest.json
> fix: upgrade transitions version to 0.8.8

- custom_components/entity_controller/__init__.py
It seems illogical that param support is specifically unavailable when calling helper functions. This makes it impossible to use a generic script that handles motion where multiple EntityControllers can pass a differentiating parameter to that script. An example might be to pass the room name to the helper function and to the script which could in turn initiate a scene using the same parameter.
Modification is restricted to handleTriggerOnDeactivateEntities and handleTriggerOnActivateEntities functions. These functions should be consistent in param handling and effectively the same changes are applied to both
```
trigger_on_activate: script.room_lights_motion
trigger_on_deactivate: script.room_lights_off
service_data:
variables:
room: "bedroom"
service_data_off:
variables:
room: "bedroom" …
```
> Add param support on helper functions

- custom_components/entity_controller/__init__.py
> Add params support to helper functions (#248)

- .github/FUNDING.yml
- README.md
- info.md
> Merge to Develop

- custom_components/entity_controller/__init__.py
> fix: resolve defect #316

- custom_components/entity_controller/__init__.py
Fixes issue introduced in HA 2024.2.0 release where test against YamlObjects types no longer work, which resulted in no configurations loading.  Fix was using isinstance() instead.
Also corrected typo in debugging statement.
Very low impact change, no logic changed.
- [ X] The PR title is clear, concise and follows [`conventional commit`](https://www.conventionalcommits.org) formatting.
- [ X] Double-check your branch is based on `develop` and targets `develop` 
- [ X] Issue raised to compliment this PR (if no pre-existing issue exists)
- [ n/a] Code is commented, particularly in hard-to-understand areas and relevant issues are referenced.
- [ n/a] Documentation repository updated to reflect new features or changes in behaviour (VERY IMPORTANT, undocumented features cannot be discovered …
> fix: parsing config files broke with HA 2024.2.0 release

- custom_components/entity_controller/__init__.py
> fix: async schedule update
